version: "3.7"
services: # 一个应用的容器，可以包括若干运行相同image的容器实例,项目标配，可以多容器
  mongodb_container:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db # data在哪里储存的

volumes:
  mongodb_data_container: # 这里volumes是和上面的volumes连接

# Image：镜像（放包里的镜像，内容不变），也就是运用系统，总是用latest
# Registry： 仓库 （背包），管理image， Docker Hub,提供image上传下载浏览等功能，提供账号管理 http://hub.Docker.com
# Container： 容器 （用魔法造好的房子）,跑项目程序，提供服务

# project: 由一组关联的容器组成的一个完整业务单元,是compose默认管理对象，通过子命令对项目中的容器管理
#  docker-compose.yml 是compose的模版文件
